/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "lilac-wash": "#a981ff",
        "secondary-container": "#0cb3ff",
        "surface-variant": "#e7e1e8",
        "outline": "#7b7487",
        "sky-tint": "#e6f4ff",
        "deep-plum": "#17082c",
        "tertiary-fixed": "#e2eb51",
        "on-secondary-container": "#004261",
        "secondary": "#006492",
        "secondary-fixed-dim": "#8bceff",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f5eff6",
        "lavender-mist": "#cab3f8",
        "surface-container": "#f2ecf3",
        "on-primary-container": "#efe4ff",
        "background": "#fef7ff",
        "inverse-surface": "#322f35",
        "on-error": "#ffffff",
        "ice-blue": "#a9dbff",
        "on-surface-variant": "#4a4455",
        "input-dark-fill": "#2d2933",
        "primary": "#611bd4",
        "surface-container-low": "#f8f2f9",
        "on-secondary": "#ffffff",
        "tertiary": "#4f5400",
        "on-tertiary-fixed-variant": "#464a00",
        "tertiary-container": "#676d00",
        "on-secondary-fixed": "#001e2f",
        "slate": "#6e6e73",
        "on-tertiary-fixed": "#1b1d00",
        "on-primary-fixed-variant": "#5700c9",
        "ink": "#19171c",
        "secondary-fixed": "#c9e6ff",
        "on-background": "#1d1b20",
        "volt": "#f5ff63",
        "surface-container-lowest": "#ffffff",
        "hairline-gray": "#e5e4e7",
        "surface-container-high": "#ece6ed",
        "surface-tint": "#7032e2",
        "on-secondary-fixed-variant": "#004b6f",
        "on-error-container": "#93000a",
        "primary-container": "#7a40ed",
        "pure-white": "#ffffff",
        "surface-bright": "#fef7ff",
        "outline-variant": "#ccc3d8",
        "studio-off-white": "#f2f1f3",
        "on-surface": "#1d1b20",
        "surface-container-highest": "#e7e1e8",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c5cf37",
        "primary-fixed-dim": "#d1bcff",
        "primary-fixed": "#e9ddff",
        "surface": "#fef7ff",
        "inverse-primary": "#d1bcff",
        "surface-dim": "#ded8df",
        "soft-mist": "#97979b",
        "on-primary-fixed": "#24005b",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e7f157"
      },
      borderRadius: {
        "card": "40px",
        "pill": "50px",
        "input": "26px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
